name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.20.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run CI command
        run: npm ci

      - name: Check linting
        run: npm run lint

      - name: Build
        run: npm run build
